
NEW_USER="insert into User (email,password,name,major,faculty,profilePic,bio) VALUES('{0}','{1}','{2}','{3}','{4}','{5}','{6}')"
NEW_GROUP="insert into Groups (tutorID,name,purpose,faculty,picture) VALUES('{0}','{1}','{2}','{3}','{4}')"
NEW_EVENT="insert into Meeting (name,location,time,date,purpose,faculty) VALUES('{0}','{1}',{2},{3},'{4}','{5}')"
USER_ID="select ID from User WHERE email='{0}' and password='{1}'"
USER_OBJ="select email, password from User WHERE ID='{0}'"
USER="SELECT * FROM User WHERE ID='{0}'"
EDIT_PROFILE="Update User SET email='{0}',name='{1}',major='{2}',faculty='{3}',password='{4}',bio='{5}' WHERE ID='{6}'"
USER_ATTENDING="SELECT * FROM User WHERE ID in (SELECT userID FROM Attending WHERE meetingID='{0}')"
EVENT="SELECT * FROM Meeting WHENEVER ID='{0}'"
COLLEAGUES="SELECT * FROM User WHERE ID in (SELECT colleagueID FROM Colleagues WHERE userID='{0}')"
FOLLOW="INSERT INTO Colleagues VALUES ('{0}','{1}')"
UNFOLLOW="DELETE FROM Colleagues WHERE userID='{0}' and colleagueID='{1}'"
USER_EVENTS="SELECT * FROM Meeting WHERE ID in (SELECT meetingID FROM Attending WHERE userID='{0}')"
USER_GROUPS="SELECT * FROM Groups WHERE ID in (SELECT groupID from Belongs WHERE userID='{0}')"
